### ISSUE TITLE
Code completion over SSH

### ISSUE THREAD

**Issue by gedw99** [bryphe/oni#834] opened 2017-10-28 08:42 UTC
I work on osx, but have to also code on Linux ( running inside vagrant ).

Can I work on golang code residing on the Linux server from osx with Oni ?
Am looking for code completion.

Because neovim drives it's frontend GUI via RPC, and this RPC is transport agnostic i would assume that all the Linux server needs is neovim installed ?

**Comment by bryphe** [comment] 2017-10-30 23:18
Hi @gedw99 ,

Thanks for logging the issue! There's actually some discussion about this in issue #247 . Oni uses [language servers](http://langserver.org/) to power some of the rich completion scenarios - so we'd need to think about where those are run. We're thinking through some of the ideas there - for example, having Oni run on the linux machine, and connect to it via OS X. Another possibility is that, since language servers support opening files based on `URIs`, we could potentially run the language server on OSX.

It'd be relatively straightforward to simply connect to a running Neovim instance remotely - we just have to think through how the language server support will work.  

I'll close this as a duplicate of #247 - feel free to add thoughts there!

**Closed by bryphe** 2017-10-30 23:18 UTC
