### ISSUE TITLE
Underscores aren't being displayed

### ISSUE THREAD

**Issue by keforbes** [bryphe/oni#162] opened 2017-01-13 20:48 UTC
![underscore](https://cloud.githubusercontent.com/assets/817509/21945116/c054ef70-d996-11e6-80cb-fd859939ed94.png)

In the screenshot above, notice that the QuickInfo shows `_pluginManager` yet the word appears to be `pluginManager` with a space in front of it.  For all those variables, there's supposed to be a `_` between `this.` and the name.  If you try typing a `_` it looks like a space.

**Comment by extr0py** [comment] 2017-01-14 03:28
Weird! Definitely a bug, thanks for the screenshot:

1) What OS is this?
2) Did you customize the font / font size? If so, what are the settings for that?

**Comment by extr0py** [comment] 2017-01-14 03:38
Also, I wonder if the DOM rendering PR (#140) fixes this

**Comment by keforbes** [comment] 2017-01-14 05:52
This is Linux, no customization to any fonts.  Are you not able to reproduce it?  Is this only me?

**Comment by extr0py** [comment] 2017-01-14 06:21
Wasn't able to repro it on Windows! But I just tried on an Ubuntu Linux box and was able to repro, same behavior

**Comment by Rafi993** [comment] 2017-01-14 14:52
I tried typing _ on oni and saved it and opened it in another editor it seems to be showing up in the file.

**Comment by Rafi993** [comment] 2017-01-14 15:34
It is mostly electron rendering issue there was a simiar issue https://github.com/atom/atom/issues/8026 some time ago

**Comment by extr0py** [comment] 2017-01-16 20:31
Looks like the DOM rendering PR i'm working on in #140 helps this

**Comment by keforbes** [comment] 2017-01-17 17:02
Just updated and things look much better.  I'm now only seeing the occasional issue where the underscore disappears when the cursor is on the line **below** the underscore.  This causes underscores to flicker as I `jjjjjj` in a file.  Test with the private variables declared at the beginning of the `NeovimInstance` class declaration.

![underscore](https://cloud.githubusercontent.com/assets/817509/22030696/adeef29c-dc9b-11e6-8828-f3cab3d09553.png)

**Comment by keforbes** [comment] 2017-03-06 18:21
I'm not seeing the issue in my previous comment anymore.  I don't know if it was due to upgrading Electron or some other change but that final issue is fixed.

**Comment by extr0py** [comment] 2017-03-06 18:38
Awesome! It's possible the electron upgrade could've helped here, as they bumped up the renderer version and picked up the latest fixes from Chrome.

**Comment by hoschi** [comment] 2017-08-07 13:59
I have the same thing, but with latest release v0.2.7
![2017-08-07-155759_609x54_scrot](https://user-images.githubusercontent.com/163128/29029834-4526ad08-7b89-11e7-8bcf-e7c50e061271.png)
the text is
```js
let overrideDetailProp = setPath(R.__, R.__, defaultDetailProps);
```
I'm also on Linux like @keforbes

**Comment by hoschi** [comment] 2017-08-07 14:00
When I go into line selection mode (`V`) and back to normal mode I I see them with strange artifacts. Underscores and artifacts go away when I switch modes again or do something other.

![2017-08-07-155942_621x47_scrot](https://user-images.githubusercontent.com/163128/29029918-9904e4a8-7b89-11e7-9541-01ad8cb436e8.png)

**Comment by extr0py** [comment] 2017-08-07 14:57
Thanks for the screenshots, @hoschi ! I have seen this occasionally, but not able to reproduce it consistently. I think the default color scheme hides it a bit - when I switch to another color scheme, the problem shows up more. So your screenshots were really helpful. Which colorscheme are you using, btw?

This is certainly a regression from the switch from DOM Rendering -> Canvas Rendering. It looks to me like there might be a rounding error when we're drawing / clearing some of the rectangles around text.

**Comment by extr0py** [comment] 2017-08-07 14:59
In regards to the underscore - it looks like the text measurement may not be completely accurate. For the canvas rendering strategy, the character sizing has to be precise - I believe the character measuring logic might not be handling descenders correctly.

**Comment by hoschi** [comment] 2017-08-07 15:23
@extr0py 
I use a [solarized](https://github.com/lifepillar/vim-solarized8 ) theme:
```VimL
set background=light
colorscheme solarized8_light_high
```

**Comment by cyansprite** [comment] 2017-08-09 15:02
I also have this issue...
Whenever I use j and move past the line it disappears, but if use k and go back up it, it reappears...

**Comment by bryphe** [comment] 2017-10-03 01:05
This was fixed by PR #731 and is in the [v0.2.10](https://github.com/bryphe/oni/releases/tag/v0.2.10-recovery) release. Feel free to log a new issue if you're still seeing any render artifacts (this one is a bit overloaded 😄 )

**Closed by bryphe** 2017-10-03 01:05 UTC
Labels: bug, daily-editor-blocker, difficulty:medium, help wanted

**Comment by city41** [comment] 2018-05-30 22:51
I am seeing a similar issue on Oni 0.3.4.

I am on Linux, and finding underscores don't really render anything. I can tell they are there because the next letter jumps ahead a space.

![image](https://user-images.githubusercontent.com/141159/40751717-4326ae28-6421-11e8-9252-63e48469b9ad.png)

If I do a search for underscores ie `/_<CR>`, they highlight:

![image](https://user-images.githubusercontent.com/141159/40751744-5b1441ee-6421-11e8-92db-f60683b8e0af.png)

**Comment by city41** [comment] 2018-05-30 22:57
false alarm, I updated my comment above. sorry everyone :)
